name: HorsinAround
main: fun.sunrisemc.horses.Plugin
version: 0.0.1
api-version: 1.20
authors: ["TheFishNextDoor"]
description: More entity information
commands:
  entityinfo:
    description: Get information about an entity
    usage: /entityinfo
    permission: horsinaround.entityinfo